[programs.devnet]
myepicproject = "969LoebfA2i4DsrPXqUdHEv2aXd9XWrJgkcwgoPbVitE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/fdm/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
